/*
* Author:	Sebastian Wolf
* Created:	August 2018
*/

#ifndef FUEHRERSTANDSANZEIGEN_H
#define FUEHRERSTANDSANZEIGEN_H

#define keine_Funktion 0x00
#define Geschwindigkeit 0x01
#define Druck_Hauptluftleitung 0x02
#define Druck_Bremszylinder 0x03
#define Druck_Hauptluftbehaelter 0x04
#define Luftpresser_laeuft 0x05
#define Luftstrom_Fvb 0x06
#define Luftstrom_Zbv 0x07
#define Luefter_an 0x08
#define Zugkraft_gesamt 0x09
#define Zugkraft_pro_Achse 0x0A
#define Zugkraft_Soll_gesamt 0x0B
#define Zugkraft_Soll_pro_Achse 0x0C
#define Oberstrom 0x0D
#define Fahrleitungsspannung 0x0E
#define Motordrehzahl 0x0F
#define Uhrzeit_Stunde 0x10
#define Uhrzeit_Minute 0x11
#define Uhrzeit_Sekunde 0x12
#define Hauptschalter 0x13
#define Trennschütz 0x14
#define Fahrstufe 0x15
#define _3D_Fenster 0x16
#define AFB_Sollgeschwindigkeit 0x17
#define Druck_Hilfsluftbehaelter 0x18
#define Zurueckgelegter_Gesamtweg 0x19
#define LM_Getriebe 0x1A
#define LM_Schleudern 0x1B
#define LM_Gleiten 0x1C
#define LM_Mg_Bremse 0x1D
#define LM_H_Bremse 0x1E
#define LM_R_Bremse 0x1F
#define LM_Hochabbremsung 0x20
#define LM_Schnellbremsung 0x21
#define Status_Notbremsung 0x22
#define LM_Uhrzeit_digital 0x23
#define LM_Drehzahlverstellung 0x24
#define LM_Fahrtrichtung_vor 0x25
#define LM_Fahrtrichtung_zurueck 0x26
#define LM_Fahrtrichtung_M 0x27
#define Hintergrundbild 0x28
#define Motordrehmoment 0x29
#define Motorlast_normiert 0x2A
#define Tunnel 0x2B
#define Schienenstoß_Weiche 0x2C
#define Stahlbruecke 0x2D
#define Steinbruecke 0x2E
#define x_Koordinate 0x2F
#define y_Koordinate 0x30
#define z_Koordinate 0x31
#define UTM_Referenzpunkt_x 0x32
#define UTM_Referenzpunkt_y 0x33
#define UTM_Zone 0x34
#define UTM_Zone_2 0x35
#define AFB_an 0x36
#define Fahrpultintern_01 0x37
#define Fahrpultintern_02 0x38
#define Fahrpultintern_03 0x39
#define Fahrpultintern_04 0x3A
#define Fahrpultintern_05 0x3B
#define Fahrpultintern_06 0x3C
#define Fahrpultintern_07 0x3D
#define Fahrpultintern_08 0x3E
#define Fahrpultintern_09 0x3F
#define Fahrpultintern_10 0x40
#define Fahrpultintern_11 0x41
#define Fahrpultintern_12 0x42
#define Fahrpultintern_13 0x43
#define Fahrpultintern_14 0x44
#define Fahrpultintern_15 0x45
#define Fahrpultintern_16 0x46
#define Fahrpultintern_17 0x47
#define Fahrpultintern_18 0x48
#define Fahrpultintern_19 0x49
#define Fahrpultintern_20 0x4A
#define Datum 0x4B
#define Gleiskruemmung 0x4C
#define Streckenhoechstgeschwindigkeit 0x4D
#define Zugkraftvorschlag_Autopilot 0x4E
#define Beschleunigung_x 0x4F
#define Beschleunigung_y 0x50
#define Beschleunigung_z 0x51
#define Drehbeschleunigung_x_Achse 0x52
#define Drehbeschleunigung_y_Achse 0x53
#define Drehbeschleunigung_z_Achse 0x54
#define Stromabnehmer 0x55
#define LM_Federspeicherbremse 0x56
#define Zustand_Federspeicherbremse 0x57
#define Steuerwagen_LM_Getriebe 0x58
#define Steuerwagen_LM_Schleudern 0x59
#define Steuerwagen_LM_Gleiten 0x5A
#define Steuerwagen_LM_H_Bremse 0x5B
#define Steuerwagen_LM_R_Bremse 0x5C
#define Steuerwagen_LM_Drehzahlverstellung 0x5D
#define Druck_Zeitbehaelter 0x5E
#define Geschwindigkeit_absolut 0x5F
#define Zug_ist_entgleist 0x60
#define Kilometrierung_Zugspitze 0x61
#define Motorstrom 0x62
#define Motorspannung 0x63
#define Status_Sifa 0x64
#define Status_Zugbeeinflussung 0x65
#define Status_Tueren 0x66
#define Fahrpultintern_21 0x67
#define Fahrpultintern_22 0x68
#define Fahrpultintern_23 0x69
#define Fahrpultintern_24 0x6A
#define Fahrpultintern_25 0x6B
#define Fahrpultintern_26 0x6C
#define Fahrpultintern_27 0x6D
#define Fahrpultintern_28 0x6E
#define Fahrpultintern_29 0x6F
#define Fahrpultintern_30 0x70
#define Fahrpultintern_31 0x71
#define Fahrpultintern_32 0x72
#define Fahrpultintern_33 0x73
#define Fahrpultintern_34 0x74
#define Fahrpultintern_35 0x75
#define Fahrpultintern_36 0x76
#define Fahrpultintern_37 0x77
#define Fahrpultintern_38 0x78
#define Fahrpultintern_39 0x78
#define Fahrpultintern_40 0x7A
#define Steuerwagen_Luefter_an 0x7B
#define Steuerwagen_Zugkraft_gesamt 0x7C
#define Steuerwagen_Zugkraft_pro_Achse 0x7D
#define Steuerwagen_Zugkraft_Soll_gesamt 0x7E
#define Steuerwagen_Zugkraft_Soll_pro_Achse 0x7F
#define Steuerwagen_Oberstrom 0x80
#define Steuerwagen_Fahrleitungsspannung 0x81
#define Steuerwagen_Motordrehzahl 0x82
#define Steuerwagen_Hauptschalter 0x83
#define Steuerwagen_Trennschueütz 0x84
#define Steuerwagen_Fahrstufe 0x85
#define Steuerwagen_Motordrehmoment 0x86
#define Steuerwagen_Motorlast_normiert 0x87
#define Steuerwagen_Stromabnehmer 0x88
#define Steuerwagen_Motorstrom 0x89
#define Steuerwagen_Motorspannung 0x8A
#define Geschwindigkeit_absolut_inkl_Schleudern 0x8B
#define Batteriehauptschalter_aus 0x8C
#define Status_Fahrzeug 0x8D
#define Status_Zugverband 0x8E
#define Bremsprobefunktion 0x8F
#define Zug_und_BremsGesamtkraftsoll_normiert 0x90
#define Steuerwagen_Zug_und_BremsGesamtkraftsoll_normiert 0x91
#define Status_Weichen 0x92
#define Zug_und_BremsGesamtkraftsoll_absolut_normiert 0x93
#define Steuerwagen_Zug_und_BremsGesamtkraftsoll_absolut_normiert 0x94
#define Fahrzeugintern_01 0x95
#define Fahrzeugintern_02 0x96
#define Fahrzeugintern_03 0x97
#define Fahrzeugintern_04 0x98
#define Fahrzeugintern_05 0x99
#define Fahrzeugintern_06 0x9A
#define Fahrzeugintern_07 0x9B
#define Fahrzeugintern_08 0x9C
#define Fahrzeugintern_09 0x9D
#define Fahrzeugintern_10 0x9E
#define Fahrzeugintern_11 0x9F
#define Fahrzeugintern_12 0xA0
#define Fahrzeugintern_13 0xA1
#define Fahrzeugintern_14 0xA2
#define Fahrzeugintern_15 0xA3
#define Fahrzeugintern_16 0xA4
#define Fahrzeugintern_17 0xA5
#define Fahrzeugintern_18 0xA6
#define Fahrzeugintern_19 0xA7
#define Fahrzeugintern_20 0xA8

#endif
